version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: $PWD/services/frontend
      dockerfile: ./docker/Dockerfile
      args:
        user: "node"
        group: "node"
    restart: "no"
    network_mode: host
    ports: 
      # Nuxt default port
      - 3000:3000
    volumes:
      - $PWD/services/frontend/app/src:/home/node/app/src
    entrypoint: ["npm","run","generate"]